apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: stock-portfolio
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31322
  type: NodePort
