apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: stock-portfolio
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb